name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build-macos-arm64:
    name: Build macOS arm64
    runs-on: macos-14
    strategy:
      matrix:
        architecture: ['arm64']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          brew install autoconf
          brew install automake
          brew install wget
          wget https://github.com/aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0.tar.gz
          tar -zxf aria2-1.37.0.tar.gz
          cd aria2-1.37.0
          sed -i '' 's/"1", 1, 16/"128", 1, -1/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/"20M", 1_m, 1_g/"4K", 1_k, 1_g/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/PREF_CONNECT_TIMEOUT, TEXT_CONNECT_TIMEOUT, "60", 1, 600/PREF_CONNECT_TIMEOUT, TEXT_CONNECT_TIMEOUT, "30", 1, 600/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/PREF_PIECE_LENGTH, TEXT_PIECE_LENGTH, "1M", 1_m, 1_g/PREF_PIECE_LENGTH, TEXT_PIECE_LENGTH, "4k", 1_k, 1_g/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/new NumberOptionHandler(PREF_RETRY_WAIT, TEXT_RETRY_WAIT, "0", 0, 600/new NumberOptionHandler(PREF_RETRY_WAIT, TEXT_RETRY_WAIT, "2", 0, 600/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/new NumberOptionHandler(PREF_SPLIT, TEXT_SPLIT, "5", 1, -1,/new NumberOptionHandler(PREF_SPLIT, TEXT_SPLIT, "8", 1, -1,/g' ./src/OptionHandlerFactory.cc
          cp ../makerelease-osx-v2.mk ./
          mkdir build-release
          cd build-release
          ln -s ../makerelease-osx-v2.mk Makefile
          make ARCH=${{ matrix.architecture }}
          cd aria2-def/bin
          tar -zcf aria2c_darwin_arm64.tar.gz aria2c
          cp aria2c_darwin_arm64.tar.gz ${{ github.workspace }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aria2c_darwin_arm64
          path: aria2c_darwin_arm64.tar.gz
          
  build-macos-x86_64:
    name: Build macOS x86_64
    runs-on: macos-13
    strategy:
      matrix:
        architecture: ['x86_64']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          brew install autoconf
          brew install automake
          brew install wget
          wget https://github.com/aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0.tar.gz
          tar -zxf aria2-1.37.0.tar.gz
          cd aria2-1.37.0
          sed -i '' 's/"1", 1, 16/"128", 1, -1/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/"20M", 1_m, 1_g/"4K", 1_k, 1_g/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/PREF_CONNECT_TIMEOUT, TEXT_CONNECT_TIMEOUT, "60", 1, 600/PREF_CONNECT_TIMEOUT, TEXT_CONNECT_TIMEOUT, "30", 1, 600/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/PREF_PIECE_LENGTH, TEXT_PIECE_LENGTH, "1M", 1_m, 1_g/PREF_PIECE_LENGTH, TEXT_PIECE_LENGTH, "4k", 1_k, 1_g/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/new NumberOptionHandler(PREF_RETRY_WAIT, TEXT_RETRY_WAIT, "0", 0, 600/new NumberOptionHandler(PREF_RETRY_WAIT, TEXT_RETRY_WAIT, "2", 0, 600/g' ./src/OptionHandlerFactory.cc
          sed -i '' 's/new NumberOptionHandler(PREF_SPLIT, TEXT_SPLIT, "5", 1, -1,/new NumberOptionHandler(PREF_SPLIT, TEXT_SPLIT, "8", 1, -1,/g' ./src/OptionHandlerFactory.cc
          cp ../makerelease-osx-v2.mk ./
          mkdir build-release
          cd build-release
          ln -s ../makerelease-osx-v2.mk Makefile
          make ARCH=${{ matrix.architecture }}
          cd aria2-def/bin
          tar -zcf aria2c_darwin_amd64.tar.gz aria2c
          cp aria2c_darwin_amd64.tar.gz ${{ github.workspace }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aria2c_darwin_amd64
          path: aria2c_darwin_amd64.tar.gz

  upload-artifacts:
    needs: [build-macos-arm64, build-macos-x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: |
          echo "Downloaded artifacts:"
          find artifacts -type f -name "*.tar.gz" | sort

      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: aria2c-builds
          path: artifacts/*/aria2c_darwin_*.tar.gz